### ISSUE TITLE
Start GS/OS from P8 on HD

### ISSUE THREAD

**Issue by fadden** [ibrumby/Crossrunner-Issues#1]
I'm not sure if this is a bug, but it's different behavior.

For many years I booted my IIgs into ProDOS 8, and launched GS/OS from there.  The GS/OS "ProDOS" file gets renamed to "ProDOS.GSOS" and executed.

For some obscure reason, you couldn't just launch it from ProSel.   You have to start BASIC.System and run it from Applesoft, or things go wrong.

This worked fine on my ROM 01 machine and in an old version of KEGS.  It works on a 3.5" disk in Crossrunner.  It does not work from an HD image in Crossrunner, either ROM 01 or ROM 03.

I'm attaching a couple of disk images.  Steps to reproduce:
 - Insert disk, boot
 - Select "Boot GS/OS" in ProSel-8 and hit return.

If I use the 3.5" disk image, I get the expected failure: "Unable to load START.GS.OS" and a bouncing apple with error $0046.  (I didn't include most of GS/OS.)

If I use the HD image, I get "?BAD SUBSCRIPT ERROR IN 100" instead.

[CrossTest.ZIP](https://github.com/ibrumby/Crossrunner-Issues/files/13780840/CrossTest.ZIP)

**Comment by ibrumby** [comment]
I can replicate the BAD SUBSCRIPT ERROR under emulation, and verified that it comes up with a different error on my ROM03 real hardware. I'll have a look at what is going on there.

**Comment by ibrumby** [comment]
I found the problem. It's in my Smartport firmware, rather than the emulator. The firmware is not setting address $07F8 to be the slot after calls to $C70A or $C70D.
