### ISSUE TITLE
Fatal System Error 0911 with ROM 01 and SCSI card

### ISSUE THREAD

**Issue by fadden** [ibrumby/Crossrunner-Issues#10]
Right-click My System, Edit, configure for ROM 03 with empty slots, but put a SCSI card in slot 7.  No disk or hard drive images. Click OK, then right-click and Run.  Result: "Check startup device!".

Repeat procedure with ROM 01.  Result: "Fatal system error-> 0911".  I believe that's supposed to indicate an ADB failure.

![config](https://github.com/ibrumby/Crossrunner-Issues/assets/6185696/eb8d1a88-f82e-4e07-9707-cd25f3707379)

If you put a disk image in S7D1, the system boots as expected.

**Comment by ibrumby** [comment]
This will take a while to figure out.
