### ISSUE TITLE
Internet software search yields no results

### ISSUE THREAD

**Issue by IvanExpert** [ibrumby/Crossrunner-Issues#25]
Using the Download title(s) from internet feature, no matter what I enter into any field, no results are returned.

Have tried on two computers, both running Parallels Desktop on Mac (one Intel, one ARM).

**Comment by g051051** [comment]
I had the same problem, but I think the fields are case sensitive.  I had to use things like "Brutal Deluxe" and "Airheart" and "Choplifter" to get results.  "Robotwar" and "robotwar" don't work, but "RobotWar" does.

**Comment by ibrumby** [comment]
Thanks for the bug report relating to case sensitivity.

**Comment by ibrumby** [comment]
This has been fixed and will be included in the next release.

**Comment by IvanExpert** [comment]
Can confirm that when using correct case, search results come up.
