### ISSUE TITLE
Crossrunner crashes after failed attempt to download title(s) from the internet

### ISSUE THREAD

**Issue by g051051** [ibrumby/Crossrunner-Issues#29]
Crossrunner crashes when trying to download images and encountering some kind of connectivity issue.  If I attempt to ask it to download several titles, sometimes one of the downloads will fail, and it will start rapidly creating dozens (or hundreds) of popup error boxes.  My system becomes unresponsive while this is happening, until eventually it completely crashes or is terminated by the OS (Windows 11).

**Comment by ibrumby** [comment]
Thanks for reporting the bug. It has now been fixed and will be included in the next release.

**Comment by g051051** [comment]
It's been 19 months since this was fixed, will there ever be another release?
