### ISSUE TITLE
AppleLink hangs during boot

### ISSUE THREAD

**Issue by fadden** [ibrumby/Crossrunner-Issues#7]
AppleLink PE hangs during boot.  It comes most of the way up, then stalls with the 3.5" drive showing T66 S1.  Tried with ROM01 and ROM03.

It works with my old copy of KEGS.  I was attempting to see if the emulator handled a softswitch edge case (https://groups.google.com/g/comp.sys.apple2/c/Z32q2D_oKF8/m/wdglvmKyAwAJ).

Disk image: [AppleLink.ZIP](https://github.com/ibrumby/Crossrunner-Issues/files/13798677/AppleLink.ZIP)

**Comment by ibrumby** [comment]
It works for me as long as serial port 2 is connected to something. If it is disconnected then it hangs.

**Comment by fadden** [comment]
I tried setting the modem port to TCP/IP, no change.  Does it need something actively talking to it?

**Comment by ibrumby** [comment]
Yes, you need something connected on the other end. AppleLink is testing DCD, so it in theory needs a connection. However, I can see on real hardware that the disk boots with no serial cable attached, so I think my handling of DCD with no cable attached is wrong. I'm trying to verify the schematic.
